---
title: "Activity 7 - Linear Discriminant Analysis"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 2: Load the necessary packages

```{r load-packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(tidymodels)
library(discrim)
```

## Task 3: Load the data and

```{r load-data-and, warning=FALSE, message=FALSE}
resume <- readr::read_csv("https://www.openintro.org/data/csv/resume.csv")
```

Answer the following question:

1.  TODO: Add answer here

## Task 4: LDA

```{r lda}
# Convert received_callback to a factor with more informative labels
resume <- resume %>% 
  mutate(received_callback = factor(received_callback, labels = c("No", "Yes")))

# LDA
lda_years <- discrim_linear() %>% 
  set_mode("classification") %>% 
  set_engine("MASS") %>% 
  fit(received_callback ~ log(years_experience), data = resume)

lda_years
```

## Task 5: Predictions

```{r prediction}
predict(lda_years, new_data = resume, type = "prob")
```

```{r confusion-matrix}
augment(lda_years, new_data = resume) %>% 
  conf_mat(truth = received_callback, estimate = .pred_class)
```

```{augment(lda_years, new_data = resume) %>%}
  accuracy(truth = received_callback, estimate = .pred_class)
```

## Challenge: Compare with logistic regression

Fit a similar model as we just explored, but instead using logistic regression. Discuss how the results are similar and different.

```{r}
# TODO: perform logistic regression

```
